# Generated by Django 4.2.4 on 2023-10-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteVitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255)),
                ('site_description', models.TextField()),
                ('keywords', models.TextField()),
                ('update_date', models.DateField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteVitrine.site')),
            ],
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('active', 'Actif')], max_length=10)),
                ('expiration_date', models.DateField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteVitrine.site')),
            ],
        ),
    ]
