# Generated by Django 4.2.4 on 2023-10-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('site_url', models.URLField()),
                ('description', models.TextField()),
                ('site_status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], max_length=10)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('page_content', models.TextField()),
                ('display_order', models.IntegerField()),
                ('page_status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], max_length=10)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVitrine.site')),
            ],
        ),
    ]
