# Generated by Django 4.2.4 on 2023-10-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteVitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_file', models.FileField(upload_to='templates/')),
                ('author', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('section_content', models.TextField()),
                ('display_order', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteVitrine.site')),
            ],
        ),
    ]
